"""feat(debate): add max_turns column

Revision ID: d1d3c191b89e
Revises: 4d8ee91ef92a
Create Date: 2026-10-01 13:35:01.596930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d3c191b89e'
down_revision: Union[str, Sequence[str], None] = '4d8ee91ef92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debates', sa.Column('max_turns', sa.Integer(), server_default='6', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debates', 'max_turns')
    # ### end Alembic commands ###
