"""empty message

Revision ID: f083890f3335
Revises: 
Create Date: 2026-08-29 13:35:59.964570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f083890f3335'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debates',
    sa.Column('debate_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('proposition_model', sa.String(), nullable=False),
    sa.Column('opposition_model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('debate_state', sa.Enum('ACTIVE', 'PAUSED', 'SUMMARIZING', 'COMPLETE', name='debatestate'), nullable=False),
    sa.PrimaryKeyConstraint('debate_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('debate_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('PROPOSITION', 'OPPOSITION', 'HUMAN', 'SUMMARIZER', name='messagerole'), nullable=False),
    sa.Column('message_type', sa.Enum('DEBATE_TURN', 'HUMAN_INJECTION', 'SUMMARY', name='messagetype'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['debate_id'], ['debates.debate_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('debates')
    # ### end Alembic commands ###
